config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users, controllers: {registrations: "registrations", sessions: "sessions"}

  resources :find_games, only: [:new, :index]
  resources :games, only: [:show, :new, :create, :destroy]
  resources :headers
  resources :lock_games
  resources :payment_options, only: [:new, :create, :edit, :update]
  resources :payments, only: [:edit, :update]
  resources :scores
  resources :squares, only: [:update]
  resources :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/score.rb
# frozen_string_literal: true

class Score < ApplicationRecord
  Y_AXIS_TEAM_NAME = "Patriots"
  X_AXIS_TEAM_NAME = "Seahawks"


  validates :x_axis_score, :y_axis_score, presence: true
  validates :quarter, presence: true, inclusion: { in: [1, 2, 3, 4] }

  def display_quarter
    { 1 => "First", 2 => "Second", 3 => "Third", 4 => "Fourth" }[quarter]
  end

  def self.quarter_scores
    select("DISTINCT ON (quarter) quarter, x_axis_score, y_axis_score, updated_at")
    .order("quarter, updated_at DESC")
  end
end

app/controllers/scores_controller.rb
# frozen_string_literal: true

class ScoresController < ApplicationController
  before_action :authenticate_user!
  before_action :set_previous_score, only: [:new]

  def index
    @scores = Score.all.order(:created_at)
  end

  def edit
    @score = Score.find(params[:id])
  end

  def update
    @score = Score.find(params[:id])
    @score.update(score_params)
  end

  def new
    @score = Score.new(previous_score_params)
  end

  def create
    @score = Score.new(score_params)
    @score.save
  end

  private

  def authenticate_user!
    render file: "#{Rails.root}/public/403.html", status: :forbidden unless current_user.admin?
  end

  def score_params
    params.require(:score).permit(:x_axis_score, :y_axis_score, :quarter, :final)
  end

  def set_previous_score
    @previous_score = Score.last_by(:created_at)
  end

  def previous_score_params
    @previous_score&.attributes&.slice("x_axis_score", "y_axis_score", "quarter") || { x_axis_score: 0, y_axis_score: 0, quarter: "First" }
  end
end

app/views/scores/_form.html.erb
<div class="relative w-full max-w-sm px-8 pt-6 pb-8 mx-auto mt-4 mb-4 bg-white border rounded shadow-md">
    <%= link_to scores_path, class: "absolute top-2 right-2 text-gray-700" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
      </svg>
    <% end %>
    <%= form_for score do |f| %>
      <div class="mb-4">
        <%= f.label Score::X_AXIS_TEAM_NAME, class: "block text-sm text-gray-700 font-medium" %>
        <%= f.number_field :x_axis_score,
          type: :tel,
          class: "w-full mt-1 px-3 py-2 leading-tight text-gray-700 border border-none rounded shadow appearance-none bg-gray-100 focus:outline-none focus:ring focus:ring-blue-500" %>
      </div>

      <div class="mb-4">
        <%= f.label Score::Y_AXIS_TEAM_NAME, class: "block text-sm text-gray-700 font-medium" %>
        <%= f.number_field :y_axis_score,
          type: :tel,
          class: "w-full mt-1 px-3 py-2 leading-tight text-gray-700 border border-none rounded shadow appearance-none bg-gray-100 focus:outline-none focus:ring focus:ring-blue-500"  %>
      </div>

      <div class="mb-4">
        <%= f.label :quarter, class: "block text-sm text-gray-700 font-medium" %>
        <%= f.select :quarter,
          [["First", 1], ["Second", 2], ["Third", 3], ["Fourth", 4]],
          {},
          class: "text-black block w-full mt-1 rounded-md bg-gray-100 border-transparent focus:border-gray-500 focus:bg-white focus:ring-0" %>
      </div>

      <div class="mb-4">
        <%= f.submit f.object.persisted? ? "Update" : "Create", class: "button w-full" %>
      </div>
    <% end %>
  </div>

app/views/scores/_nav.html.erb
<%= link_to user_path(current_user), data: { turbo: false } do %>
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8">
    <path stroke-linecap="round" stroke-linejoin="round" d="m2.25 12 8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
  </svg>
<% end %>
<% if current_user.admin? %>
  <div class="flex justify-center p-4 mt-2">
    <%= link_to "Score +", new_score_path, class: "button ml-4" %>
  </div>
<% end %>

app/views/scores/_score.html.erb
<div class="p-4"><%= score.x_axis_score %></div>
<div class="p-4"><%= score.y_axis_score %></div>
<div class="p-4"><%= score.display_quarter %></div>
<div class="p-4">
  <%= link_to "Edit", edit_score_path(score), class: "text-blue-500" %>
</div>

app/views/scores/create.turbo_stream.erb
<%= turbo_stream.append(:scores) do %>
  <div class="grid grid-cols-4 text-center bg-white border border-gray-300 even:bg-gray-300 last:rounded-b-md">
    <%= render @score %>
  </div>
<% end %>

<%= turbo_stream.update(:score_form) do %>
  <%= render "nav" %>
<% end %>

app/views/scores/edit.html.erb
<%= link_to "Home", user_path(current_user), class: "button ml-2" %>

<%= turbo_frame_tag :score_form do %>
  <%= render "form", score: @score %>
<% end %>

app/views/scores/index.html.erb
<%= turbo_frame_tag(:score_form, class: "flex items-center justify-center m-4 text-white") do %>
  <%= render "nav" %>
<% end %>

<div class="mx-auto md:w-1/2">
  <%= turbo_frame_tag(:scores) do %>
    <div class="grid grid-cols-4 text-center bg-white border border-gray-300 rounded-t-md">
      <div class="p-4 bg-x-axis rounded-tl-md"><%= Score::X_AXIS_TEAM_NAME %></div>
      <div class="p-4 text-white bg-y-axis"><%= Score::Y_AXIS_TEAM_NAME %></div>
      <div class="p-4">Quarter</div>
      <div class="p-4 rounded-tr-md">Final</div>
    </div>

    <% @scores.each do |score| %>
      <%= turbo_frame_tag(score, target: :score_form, class: "grid grid-cols-4 text-center bg-white border border-gray-300 even:bg-gray-300 last:rounded-b-md") do %>
        <%= render score %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/scores/new.html.erb
<%= turbo_frame_tag "score_form" do %>
  <%= render "form", score: @score %>
<% end %>

app/views/scores/update.turbo_stream.erb
<%= turbo_stream.update @score do %>
  <%= render "score", score: @score %>
<% end %>

<%= turbo_stream.update(:score_form) do %>
  <%= render "nav" %>
<% end %>