config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users, controllers: {registrations: "registrations", sessions: "sessions"}

  resources :find_games, only: [:new, :index]
  resources :games, only: [:show, :new, :create, :destroy]
  resources :headers
  resources :lock_games
  resources :payment_options, only: [:new, :create, :edit, :update]
  resources :payments, only: [:edit, :update]
  resources :scores
  resources :squares, only: [:update]
  resources :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :games, dependent: :destroy
  has_many :squares
  has_many :payments, through: :games, dependent: :destroy
  has_many :payment_options, dependent: :destroy
  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
  encrypts :email, deterministic: true

  def all_games
    Game.joins(:squares).includes(:users)
      .where(squares: { user_id: id }).or(
        Game.includes(:users).where(user_id: id)).order(created_at: :desc).distinct
  end

  def admin?
    [1, 2].include?(id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_current_user, only: [:show]

  def index
    @users = User.all
  end

  def show
    @form = Forms::FindGameForm.new
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<% if current_user.all_games.any? %>
  <div class="container max-w-sm p-4 mx-auto bg-white border rounded shadow-md">
    <div class="mb-4">
      <h2 class="flex justify-center text-2xl font-bold">Games</h2>
      <% current_user.all_games.each do |game| %>
        <div class="flex items-center p-2 border-b border-gray-700 last:border-b-0">
          <%= button_to game.share_code, game_path(game.share_code), method: :get, class: "button" %>
          <div class="ml-4 text-sm italic text-gray-600">
            <% if game.users.any? %>
              <%= game.users.map(&:name).uniq.sort.join(", ") %>
            <% else %>
              No players yet
            <% end %>
          </div>
          <% if game.user == current_user %>
            <%= button_to "Delete", game_path(game.share_code), method: :delete, data: { turbo_confirm: "Delete this game?" }, class: "text-red-500 text-sm", form: { class: "ml-auto" } %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<div class="container max-w-sm p-4 mx-auto mt-4 bg-white border rounded shadow-md">
  <%= turbo_frame_tag :user_show_form do %>
    <div class="flex flex-col justify-between gap-4">
      <%= button_to "Find Game", new_find_game_path, method: :get, class: "button w-full" %>
      <%= button_to "Create Game", new_game_path, method: :get, class: "button w-full" %>
      <% if current_user.admin? %>
        <%= button_to "Scores", scores_path, method: :get, class: "button w-full", data: { turbo: false } %>
      <% end %>
      <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "button button-red w-full", data: { turbo: false } %>
    </div>
  <% end %>
</div>