config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users, controllers: {registrations: "registrations", sessions: "sessions"}

  resources :find_games, only: [:new, :index]
  resources :games, only: [:show, :new, :create, :destroy]
  resources :headers
  resources :lock_games
  resources :payment_options, only: [:new, :create, :edit, :update]
  resources :payments, only: [:edit, :update]
  resources :scores
  resources :squares, only: [:update]
  resources :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :headers, dependent: :destroy
  has_many :squares, dependent: :destroy
  has_many :users, through: :squares
  has_many :payments, dependent: :destroy

  validates :square_price, presence: true, numericality: { greater_than: 0 }
  validate :payout_sum_must_equal_100

  before_create :create_share_code

  def x_headers
    headers.where(axis: "x").order(:position)
  end

  def y_headers
    headers.where(axis: "y").order(:position)
  end

  def squares_amount(user)
    squares.where(user: user).size * square_price
  end

  def total_squares_amount
    @total_squares_amount ||= claimed_squares * square_price
  end

  def headers_assigned?
    headers.any? { |header| header.value.present? }
  end

  private

  def payout_sum_must_equal_100
    if first_quarter_payout + second_quarter_payout + third_quarter_payout + final_payout != 100
      errors.add(:base, "Payout sum must equal 100%")
    end
  end

  def claimed_squares
    squares.where.not(user: nil).size
  end

  def create_share_code
    self.share_code = ShareCodeGenerator.build
    while Game.exists?(share_code: share_code)
      self.share_code = ShareCodeGenerator.build
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :check_current_user, only: [:show]

  def show
    @game = Game.includes(:headers, :squares).find_by!(share_code: params[:id].upcase)
    @decorated_game = Decorators::GameDecorator.new(@game)
  end

  def new
    @game = Game.new(
      square_price: 1,
      first_quarter_payout: 20,
      second_quarter_payout: 20,
      third_quarter_payout: 20,
      final_payout: 40
    )
  end


  def create
    @game = current_user.games.new(game_params)

    if @game.save
      Services::CreateSquares.new(@game).call
      Services::AssignNumbers.new(@game).call
      render turbo_stream: turbo_stream.action(:redirect, game_path(@game.share_code))
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @game = current_user.games.find_by!(share_code: params[:id])
    @game.destroy!

    render turbo_stream: turbo_stream.action(:redirect, user_path(current_user))
  end

  private

  def game_params
    params.require(:game).permit(:square_price, :first_quarter_payout, :second_quarter_payout, :third_quarter_payout, :final_payout)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_toggle_lock.html.erb
<%= button_to(game, method: :put, class: "w-full h-full", form_class: "w-full h-full", data: { turbo: false }) do %>
  <% if game.locked? %>
    Unlock
  <% else %>
    Lock
  <% end %>
<% end %>

app/views/games/new.html.erb
<%= turbo_frame_tag :user_show_form do %>
  <%= link_to user_path(current_user), class: "flex flex-row-reverse px-2 text-gray-700 text-right" do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
    </svg>
  <% end %>

  <%= form_for(@game, data: { controller: "toggle" }) do |f| %>
    <% if @game.errors.any? %>
      <div class="text-center text-red-500">
        <% @game.errors.full_messages.each do |message| %>
          <%= message %><br>
        <% end %>
      </div>
    <% end %>
    <div class="mb-4">
      <%= f.label :square_price, class: "block text-sm text-gray-700 font-medium" %>
      <div class="flex flex-row items-center">
        <span class="mr-2 text-xl text-gray-700">$</span>
        <%= f.number_field :square_price, autocomplete: "off", autofocus: true, class: "w-full mt-1 px-3 py-2 leading-tight text-gray-700 border border-none rounded shadow appearance-none bg-gray-100 focus:outline-none focus:ring focus:ring-blue-500" %>
      </div>
    </div>

      <span class="flex items-center justify-between mb-4">
        Payouts: 20% - 20% - 20% - 40%

        <div class="cursor-pointer" data-action="click->toggle#toggleHidden">
          <svg id="chevron-down" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
          </svg>
          <svg id="chevron-up" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="hidden size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 15.75 7.5-7.5 7.5 7.5" />
          </svg>
        </div>
      </span>

      <div data-toggle-target="element" class="hidden">
        <div class="mb-4">
          <%= f.label :first_quarter_payout, class: "block text-sm text-gray-700 font-medium" %>
          <div class="flex flex-row items-center">
            <%= f.number_field :first_quarter_payout, step: 1, class: "w-full mt-1 px-3 py-2 leading-tight text-gray-700 border border-none rounded shadow appearance-none bg-gray-100 focus:outline-none focus:ring focus:ring-blue-500" %>
            <span class="ml-2 text-xl text-gray-700">%</span>
          </div>
        </div>

        <div class="mb-4">
          <%= f.label :second_quarter_payout, class: "block text-sm text-gray-700 font-medium" %>
          <div class="flex flex-row items-center">
            <%= f.number_field :second_quarter_payout, step: 1, class: "w-full mt-1 px-3 py-2 leading-tight text-gray-700 border border-none rounded shadow appearance-none bg-gray-100 focus:outline-none focus:ring focus:ring-blue-500" %>
            <span class="ml-2 text-xl text-gray-700">%</span>
          </div>
        </div>

        <div class="mb-4">
          <%= f.label :third_quarter_payout, class: "block text-sm text-gray-700 font-medium" %>
          <div class="flex flex-row items-center">
            <%= f.number_field :third_quarter_payout, step: 1, class: "w-full mt-1 px-3 py-2 leading-tight text-gray-700 border border-none rounded shadow appearance-none bg-gray-100 focus:outline-none focus:ring focus:ring-blue-500" %>
            <span class="ml-2 text-xl text-gray-700">%</span>
          </div>
        </div>

        <div class="mb-4">
          <%= f.label :final_payout, class: "block text-sm text-gray-700 font-medium" %>
          <div class="flex flex-row items-center">
            <%= f.number_field :final_payout, step: 1, class: "w-full mt-1 px-3 py-2 leading-tight text-gray-700 border border-none rounded shadow appearance-none bg-gray-100 focus:outline-none focus:ring focus:ring-blue-500" %>
            <span class="ml-2 text-xl text-gray-700">%</span>
          </div>
        </div>
      </div>

    <div class="mb-4">
      <%= f.submit "Create Game", class: "button w-full" %>
    </div>
  <% end %>
<% end %>

app/views/games/show.html.erb
<div class="fixed inset-0 flex items-center justify-center text-lg text-center text-white bg-red-600 sm:hidden landscape:hidden">
  <p>Please rotate your device to landscape mode for a better experience.</p>
</div>

<div class="flex items-center ml-4 text-white">
  <%= link_to user_path(current_user) do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8">
      <path stroke-linecap="round" stroke-linejoin="round" d="m2.25 12 8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
    </svg>
  <% end %>
  <% if current_user.admin? %>
    <%= link_to "Scores", scores_path, class: "text-white ml-4", data: { target: "_top" } %>
  <% end %>
</div>

<% if @decorated_game.locked? %>
  <div class="grid w-3/4 grid-cols-5 mx-auto mb-4 text-center bg-white rounded-lg">
    <div class="p-2 border-b border-r border-gray-300"></div>
    <div class="p-2 border-b border-r border-gray-300">1st</div>
    <div class="p-2 border-b border-r border-gray-300">2nd</div>
    <div class="p-2 border-b border-r border-gray-300">3rd</div>
    <div class="p-2 border-b border-gray-300">Final</div>

    <div class="p-2 border-b border-l border-r border-gray-300 bg-x-axis"><%= Score::X_AXIS_TEAM_NAME %></div>
    <div class="p-2 border-b border-r border-gray-300"><%= @decorated_game.first_quarter_x_axis_score %></div>
    <div class="p-2 border-b border-r border-gray-300"><%= @decorated_game.second_quarter_x_axis_score %></div>
    <div class="p-2 border-b border-r border-gray-300"><%= @decorated_game.third_quarter_x_axis_score %></div>
    <div class="p-2 border-b border-gray-300"><%= @decorated_game.fourth_quarter_x_axis_score %></div>

    <div class="p-2 text-white border-b border-l border-r border-gray-300 bg-y-axis"><%= Score::Y_AXIS_TEAM_NAME %></div>
    <div class="p-2 border-b border-r border-gray-300"><%= @decorated_game.first_quarter_y_axis_score %></div>
    <div class="p-2 border-b border-r border-gray-300"><%= @decorated_game.second_quarter_y_axis_score %></div>
    <div class="p-2 border-b border-r border-gray-300"><%= @decorated_game.third_quarter_y_axis_score %></div>
    <div class="p-2 border-b border-gray-300"><%= @decorated_game.fourth_quarter_y_axis_score %></div>

    <div class="p-2 border-b border-r border-gray-300">🏆</div>
    <div class="p-2 border-b border-r border-gray-300"><%= @decorated_game.first_winner %></div>
    <div class="p-2 border-b border-r border-gray-300"><%= @decorated_game.second_winner %></div>
    <div class="p-2 border-b border-r border-gray-300"><%= @decorated_game.third_winner %></div>
    <div class="p-2 border-b border-gray-300"><%= @decorated_game.fourth_winner %></div>

    <div class="p-2 border-r border-gray-300">💰</div>
    <div class="p-2 border-r border-gray-300"><%= number_to_currency(@decorated_game.first_amount) %></div>
    <div class="p-2 border-r border-gray-300"><%= number_to_currency(@decorated_game.second_amount) %></div>
    <div class="p-2 border-r border-gray-300"><%= number_to_currency(@decorated_game.third_amount) %></div>
    <div class="p-2"><%= number_to_currency(@decorated_game.fourth_amount) %></div>
  </div>
<% else  %>
  <div class="flex items-center justify-center w-10/12 mx-auto mb-4">
    <%= render CardComponent.new do  %>
      <div class="flex p-1">
        <span class="font-light">Share Code:</span> <span class="ml-2 font-bold"><%= @decorated_game.share_code %></span>
      </div>
      <%= turbo_frame_tag(:payment_options, class: "flex flex-col") do %>
        <% @decorated_game.user.payment_options.each do |payment_option| %>
          <%= turbo_frame_tag(payment_option) do %>
            <%= render payment_option %>
          <% end %>
        <% end %>
      <% end %>
      <% if @decorated_game.user == current_user %>
        <%= turbo_frame_tag(:payment_option, class: "flex justify-center mt-2") do %>
          <%= button_to "Add Payment Option", new_payment_option_path, method: :get, class: "button border border-white" %>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="flex items-center justify-around w-10/12 mx-auto mb-4">
    <% if @decorated_game.user == current_user %>
      <%= button_to "Lock Squares and Assign Numbers", lock_game_path(@decorated_game.share_code), method: :patch, class: "button button-red border border-white", data: { turbo_confirm: "Lock this game? This cannot be undone." } %>
    <% end %>
  </div>
<% end %>

<div class="w-10/12 mx-auto mb-4">
  <div class="grid grid-cols-11 gap-1">
    <div class="bg-transparent border-none square">
    </div>
    <% @decorated_game.x_headers.sort_by(&:position).each do |header| %>
      <div class="bg-x-axis square">
        <%= header.value if @decorated_game.locked? %>
      </div>
    <% end %>
    <% @decorated_game.y_headers.sort_by(&:position).each do |header| %>
      <div class="text-white bg-y-axis square">
        <%= header.value if @decorated_game.locked? %>
      </div>
      <% @decorated_game.squares.filter { |square| square.y == header.position }.sort_by(&:x).each do |square| %>
        <%= turbo_frame_tag(square) do %>
          <%= render(SquareComponent.new(square)) %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="flex flex-col w-full mx-2 bg-white rounded-lg sm:w-3/4 sm:mx-auto">
  <div class="grid grid-cols-7 gap-1 px-4 py-2 border-b border-gray-200 border-double">
    <div class="text-center">Name</div>
    <div class="text-center">Squares</div>
    <div class="text-center">Paid in</div>
    <div class="text-center">Winnings</div>
    <div class="text-center">Paid out</div>
    <div></div>
    <div></div>
  </div>
  <%= turbo_frame_tag(:game_payments) do %>
    <% @decorated_game.payments.each do |payment| %>
      <%= turbo_frame_tag(payment, class: "grid grid-cols-7 gap-1 px-4 py-6 border-b border-gray-200 last:border-b-0 even:bg-gray-200") do %>
        <%= render payment, payouts: @decorated_game.payouts %>
      <% end %>
    <% end %>
  <% end %>

  <div class="grid grid-cols-7 gap-1 px-4 py-2 border-t border-b border-gray-200 rounded-b-lg">
    <div class="font-bold text-center">Total</div>
    <div class="font-bold text-center">$<%= @decorated_game.total_squares_amount %></div>
    <div class="col-span-2 text-center"></div>
  </div>
</div>

app/views/games/update.turbo_stream.erb
<%= turbo_stream.replace :toggle_lock do %>
  <% render "toggle_lock", game: @game %>
<% end %>