config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users, controllers: {registrations: "registrations", sessions: "sessions"}

  resources :find_games, only: [:new, :index]
  resources :games, only: [:show, :new, :create, :destroy]
  resources :headers
  resources :lock_games
  resources :payment_options, only: [:new, :create, :edit, :update]
  resources :payments, only: [:edit, :update]
  resources :scores
  resources :squares, only: [:update]
  resources :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/header.rb
class Header < ApplicationRecord
  belongs_to :game
end

app/controllers/headers_controller.rb
class HeadersController < ApplicationController
  before_action :set_header, only: %i[ show edit update destroy ]

  # GET /headers or /headers.json
  def index
    @headers = Header.all
  end

  # GET /headers/1 or /headers/1.json
  def show
  end

  # GET /headers/new
  def new
    @header = Header.new
  end

  # GET /headers/1/edit
  def edit
  end

  # POST /headers or /headers.json
  def create
    @header = Header.new(header_params)

    respond_to do |format|
      if @header.save
        format.html { redirect_to header_url(@header), notice: "Header was successfully created." }
        format.json { render :show, status: :created, location: @header }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @header.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /headers/1 or /headers/1.json
  def update
    respond_to do |format|
      if @header.update(header_params)
        format.html { redirect_to header_url(@header), notice: "Header was successfully updated." }
        format.json { render :show, status: :ok, location: @header }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @header.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /headers/1 or /headers/1.json
  def destroy
    @header.destroy!

    respond_to do |format|
      format.html { redirect_to headers_url, notice: "Header was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_header
      @header = Header.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def header_params
      params.require(:header).permit(:game_id, :axis, :position, :value)
    end
end

app/helpers/headers_helper.rb
module HeadersHelper
end

app/views/headers/_form.html.erb
<%= form_with(model: header) do |form| %>
  <% if header.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(header.errors.count, "error") %> prohibited this header from being saved:</h2>

      <ul>
        <% header.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :game_id, style: "display: block" %>
    <%= form.text_field :game_id %>
  </div>

  <div>
    <%= form.label :axis, style: "display: block" %>
    <%= form.text_field :axis %>
  </div>

  <div>
    <%= form.label :position, style: "display: block" %>
    <%= form.number_field :position %>
  </div>

  <div>
    <%= form.label :value, style: "display: block" %>
    <%= form.number_field :value %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/headers/_header.html.erb
<div id="<%= dom_id header %>">
  <p>
    <strong>Game:</strong>
    <%= header.game_id %>
  </p>

  <p>
    <strong>Axis:</strong>
    <%= header.axis %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= header.position %>
  </p>

  <p>
    <strong>Value:</strong>
    <%= header.value %>
  </p>

</div>

app/views/headers/edit.html.erb
<h1>Editing header</h1>

<%= render "form", header: @header %>

<br>

<div>
  <%= link_to "Show this header", @header %> |
  <%= link_to "Back to headers", headers_path %>
</div>

app/views/headers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Headers</h1>

<div id="headers">
  <% @headers.each do |header| %>
    <%= render header %>
    <p>
      <%= link_to "Show this header", header %>
    </p>
  <% end %>
</div>

<%= link_to "New header", new_header_path %>

app/views/headers/new.html.erb
<h1>New header</h1>

<%= render "form", header: @header %>

<br>

<div>
  <%= link_to "Back to headers", headers_path %>
</div>

app/views/headers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @header %>

<div>
  <%= link_to "Edit this header", edit_header_path(@header) %> |
  <%= link_to "Back to headers", headers_path %>

  <%= button_to "Destroy this header", @header, method: :delete %>
</div>